services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: hacer-ai-n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Montevideo
      - TZ=America/Montevideo
      - N8n_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
  
volumes:
  n8n_data:
    name: n8n_data

